# ~/.config/starship.toml

# Use custom format
format = """
[$directory](bold green)$rust$package [──>](bold green) 
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
